### ISSUE TITLE
title and description should wrap

### ISSUE THREAD

**Issue by leemark** [babycommando/contemplator2000#1]
First of all, thank you for creating this awesome tool! I can really see using it regularly. I tested it with some actual h=n artwork and unfortunately the title and description seem to overflow onto the picture area. 

![download](https://user-images.githubusercontent.com/3521469/119933430-51bc3380-bf41-11eb-809a-0bf132b4bbf8.png)

**Comment by babycommando** [comment]
thanks buddy!
so, p5.js is kinda hard to work with texts, but if you press ENTER on the bigger textboxes such as the title and the description it will break the text in as much lines as you need!

::) 

I'll work more  on it, also on new templates with more formats, this is the first release of all hehe
